
     Have you ever said...

              "I'd like to donate I but can't really afford it"?
              --------------------------------------------------

     If so, I know exactly how you feel. (Broke ought to be my middle name). 
I realize that not everyone has a bundle of cash sitting around just waiting 
to be sent to software authors.
     Since my main reason for asking for donations was to upgrade from my 
current computer, I thought perhaps I would change the donation theme. (I'll 
still gladly accept cash).
     On more than one occasion I have found people who don't have cash, but 
would be willing to send my some of their "old" equipment. On considering 
this, It seems reasonable (since all I really want is to upgrade from my 
current XT).
     If you have old computer hardware that you no longer have a use for, I 
would be more than happy to accept it as a donation. I would be willing to 
take just about anything.
         Hard drives, controller cards, old video cards (even CGA), power 
supplies, cables, mains leads, old cases, motherboards, floppy drives, 
monitors, serial cards, or just about any form of hardware that might assist 
me in upgrading my system. Keep in mind that it doesn't take much to upgrade 
from an XT with CGA and a 30 meg MFM hard drive.
     Perhaps in your closet, you have an old RLL/MFM hard drive with a 
controller that's no longer compatible with your current system. Or a game 
card. Or maybe an old monitor and/or controller card. Maybe some old floppy 
drives in need of minor repair. Maybe the motherboard from before you 
upgraded to your brand new pentium <G>. Just about anything if it can be 
used on (or to build) an AT (286+) class machine.
     I would gladly accept any of these things (or just about any other 
hardware that I might find a use for), as well as any documentation that you 
have for your old hardware (even without the hardware).
     So if you're short on cash but would still like to help me out, please 
send me some of your old computer parts. If you're "local" to me I may be 
able to arrange (through the generosity of a local courier company) to have 
the parts picked up after hours (to save you postal costs).
     If you do decide to send me something, please attach a short note 
stating whether or not the part was working when you last used it. And if 
not, what was wrong with it (to the best of your recollection) so that I 
might endeavour to repair it if possible.

     What say?...

      If you can't help me "buy" it... Can you help me "build" it?
      ------------------------------------------------------------

     The address is in THDDOC.TXT or the first screen of THDINSTL.EXE or 
netmail David Muir at 1:259/423.0 through fido. Any donation, no matter how 
trivial, will be appreciated.

     Thanks..
David Muir... Author THD ProScan.
