
    To use the definitions in this file you need only select "IMPORT" from the
first screen of THDEXARC.EXE. From this point you will be presented with the
first of the definitions. Select "quit" and answer "Y" or "N" depending on
whether or not you wish to import the displayed definition.

    Note that the parameters expressed in this file are not necessarily the 
same as used internally in THDPRO.EXE.

    As well, it "is" recommended that you import the first two definitions
which are marked "INTERNAL". Most of the other definitions are duplicates of 
archivers or scanners internal to THDPRO.EXE and are included only as examples
of the format.
    It is also recommended that you use AVP (or AVPLITE) as an added virus 
scanner (the definition for AVPLITE is included in this file). This virus
scanner is consistently rated higher than most other virus scanners and has 
the ability to scan some archive types and compressed executable types
internally. Use of AVP / AVPLITE can significantly increase the odds of
detecting viruses in some compressed executable files as well as some archive
types.

    It is recommended (despite the docs) that the 2 RAR SFX definitions be 
imported, regardless of your desire to import other definitions.

    You may also find the GFXCHECK definitions handy if you wish to test JPEG 
files (or would like an alternate to GIFTEST when testing GIF files).

    A definition entry is also included for Dr Solomon's FindVirus program. 
This definition is included because nobody believed me when I said it could be 
done <G>..

Begin THDEXARC Import
Archiver
Eugene Roshal's RAR version 1.54 OS2/SFX
INTERNAL
13723
3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F










0

Begin THDEXARC Import
Archiver
Eugene Roshal's RAR version 1.55 OS2/SFX
INTERNAL
13803
3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F










0

Begin THDEXARC Import
Archiver
GFXCheck Version 1.20 (GIF test - OS/2)
EXTERNAL
0
47,49,46,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
GIF
C:\GFXCHK\GFXCHK2.EXE
C:\GFXCHK\GFXCHK2.EXE
N/A
N/A


-CC:\GFXCHK\GFXCHK.CFG -F~~F


0

Begin THDEXARC Import
Archiver
GFXCheck Version 1.20 (GIF test - DOS)
EXTERNAL
0
47,49,46,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
GIF
C:\GFXCHK\GFXCHK.EXE
C:\GFXCHK\GFXCHK.EXE
N/A
N/A


-CC:\GFXCHK\GFXCHK.CFG -F~~F


0

Begin THDEXARC Import
Archiver
GFXCheck Version 1.20 (JPEG test - OS/2)
EXTERNAL
6
4A,46,49,46,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
JPG
C:\GFXCHK\GFXCHK2.EXE
C:\GFXCHK\GFXCHK2.EXE
N/A
N/A


-CC:\GFXCHK\GFXCHK.CFG -F~~F


0

Begin THDEXARC Import
Archiver
GFXCheck Version 1.20 (JPEG test - DOS)
EXTERNAL
6
4A,46,49,46,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
JPG
C:\GFXCHK\GFXCHK.EXE
C:\GFXCHK\GFXCHK.EXE
N/A
N/A


-CC:\GFXCHK\GFXCHK.CFG -F~~F


0

Begin THDEXARC Import
Scanner
Dr. Solomon's FindVirus Version 7.56
C:\SCANNER\FINDVIRU.EXE
~~D\*.* /NOBOOT /NOPART /DOALLFILES
~~F /NOBOOT /NOPART /DOALLFILES
0

Begin THDEXARC Import
Scanner
Eugene Kaspersky's AVPLite version 2.2
C:\SCANNER\AVPLITE.EXE
~~D\*.* /P /B /M /W=~~L
~~F /M /P /B /W=~~L
0

Begin THDEXARC Import
Archiver
Info-Zip's UnZipSFX version 5.12
EXTERNAL
-49611
75,6E,7A,69,70,73,66,78,3F,3F,3F,3F,3F,3F,3F
EXE
C:\ARCHIVER\PKZIP.EXE
C:\ARCHIVER\PKUNZIP.EXE
-d -o- ~~F
-arp -ex ~~F
-ex ~~F ~~I
-z ~~F<~~I
-t ~~F
-d ~~F @~~I
-d ~~F ~~I
0

Begin THDEXARC Import
Archiver
PKWARE's ZIP SFX version 2.04g
EXTERNAL
-45
70,6B,73,66,78,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
EXE
C:\ARCHIVER\PKZIP.EXE
C:\ARCHIVER\PKUNZIP.EXE
-d -o- ~~F
-arp -ex ~~F
-ex ~~F ~~I
-z ~~F<~~I
-t ~~F
-d ~~F @~~I
-d ~~F ~~I
0

Begin THDEXARC Import
Archiver
Robert Jung's ARJ version 2.41
EXTERNAL
0
60,EA,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
ARJ
C:\ARCHIVER\ARJ.EXE
C:\ARCHIVER\ARJ.EXE
x -y -ja1 -he ~~F
a -m1 -r -je -ja1 ~~F
a -e -ja1 ~~F ~~I
c -ja- -he ~~F -z~~I
t -ja1 ~~F
d -ja1 -he ~~F !~~I
d -ja1 -he ~~F ~~I
0

Begin THDEXARC Import
Archiver
Ultra Compressor 2 revision 3.00
EXTERNAL
0
55,43,32,1A,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
UC2
C:\ARCHIVER\UC.EXE
C:\ARCHIVER\UC.EXE
E -B -F -S !BAN=OFF !RELIA=ENSURE !ARCON=OFF ~~F
AP -TST -B -F -S !ARCON=OFF ~~F
A -F -TST -B !BAN=OFF !ARCON=OFF ~~F ~~I

T -B -F -!BAN=OFF !RELIA=DETECT ~~F
D -B -F !BAN=OFF ~~F @~~I
D -B -F !BAN=OFF ~~F ~~I
0

Begin THDEXARC Import
Archiver
Eugene Roshal's RAR version 1.55
EXTERNAL
0
52,61,72,21,1A,07,00,3F,3F,3F,3F,3F,3F,3F,3F
RAR
C:\ARCHIVER\RAR.EXE
C:\ARCHIVER\RAR.EXE
x -c- -std -cfg- -y -o- -pa ~~F
a -r -std -cfg- -y -m5 -s ~~F
a -c- -std -cfg- -y -m5 ~~F ~~I
c -c- -std -cfg- -y ~~F =~~I
t -c- -std -cfg- -y -pa ~~F
d -c- -std -cfg- -y ~~F @~~I
d -c- -std -cfg- -y ~~F ~~I
0

Begin THDEXARC Import
Archiver
Eugene Roshal's RAR version 1.55 OS2/SFX
EXTERNAL
-597
52,53,46,58,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
EXE
C:\OS2RAR\RAR.EXE
C:\OS2RAR\RAR.EXE
x -c- -std -cfg- -y -o- -pa ~~F
a -r -std -cfg- -y -m5 -s ~~F
a -c- -std -cfg- -y -m5 ~~F ~~I
c -c- -std -cfg- -y ~~F =~~I
t -c- -std -cfg- -y -pa ~~F
d -c- -std -cfg- -y ~~F @~~I
d -c- -std -cfg- -y ~~F ~~I
0

Begin THDEXARC Import
Archiver
PKWare's PKZIP/PKUNZIP v2.04g
EXTERNAL
0
50,4B,03,04,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
ZIP
C:\ARCHIVER\PKZIP.EXE
C:\ARCHIVER\PKUNZIP.EXE
-d -o- ~~F
-arp -ex ~~F
-ex ~~F ~~I
-z ~~F<~~I
-t ~~F
-d ~~F @~~I
-d ~~F ~~I
0

Begin THDEXARC Import
Archiver
J I Hammarberg's Squeeze it ver 1.08.02
EXTERNAL
0
48,4C,53,51,5A,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
SQZ
C:\SQZ\SQZ.EXE
C:\SQZ\SQZ.EXE
x ~~F
a -s ~~F *.*
u /p3 ~~F ~~I
c ~~F ~~I
t ~~F
d ~~F @~~I
d ~~F ~~I
0

Begin THDEXARC Import
Archiver
H Yoshizaki's LHA version 2.55beta
EXTERNAL
2
2D,6C,68,3F,2D,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
LZH
C:\ARCHIVER\LHA.EXE
C:\ARCHIVER\LHA.EXE
x -m2 ~~F
a -r ~~F
a -m2 ~~F ~~I

t -m2 ~~F
d -m2 ~~F @~~I
d ~~F ~~I
0

Begin THDEXARC Import
Archiver
NoGate Consulting's PAK version 2.51
EXTERNAL
0
1A,0A,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
PAK
C:\ARCHIVER\PAK.EXE
C:\ARCHIVER\PAK.EXE
e /wn ~~F

a /wn ~~F ~~I

t ~~F
d ~~F @~~I
d ~~F ~~I
0

Begin THDEXARC Import
Archiver
PKWare's PKARC/PKXARC version 3.5
EXTERNAL
0
1A,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F,3F
ARC
C:\ARCHIVER\PKARC.COM
C:\ARCHIVER\PKXARC.COM
-rx ~~F

-a ~~F ~~I

-t ~~F

-d ~~F ~~I
0

Begin THDEXARC Import
Scanner
Fridrik Skulason's F-Prot version 2.19
C:\SCANNER\F-PROT.EXE
~~D\*.* /ANALYSE /APPEND /NOBREAK /NOMEM /OLD /REPORT=~~L
~~F /ANALYSE /APPEND /NOBREAK /NOMEM /OLD /REPORT=~~L
0

Begin THDEXARC Import
Scanner
ThunderByte's TBSCAN version 6.38
C:\SCANNER\TBSCAN.EXE
~~D /hr /ee=.??? /co /in /nm /ba /lo /ap /ln=~~L
~~F /hr /ee=.??? /co /in /nm /ba /lo /ap /ln=~~L
0

Begin THDEXARC Import
Scanner
McAfee's VirusScan v2.2.5e
C:\SCANNER\SCAN.EXE
~~D /SUB /ALL /NOMEM /RPTERR /REPORT ~~L
~~F /ALL /NOMEM /RPTERR /REPORT ~~L
0

Begin THDEXARC Import
Scanner
McAfee's VirusScan version 1.1.7
C:\SCANNER\SCAN.EXE
~~D /SUB /A /NOMEM /NOPAUSE /NOBREAK /NOEXPIRE
~~F /A /NOMEM /NOPAUSE /NOBREAK /NOEXPIRE
0

