#!/usr/bin/env python3
"""Pack Shatranj overlays as a variable-length atlas."""

from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path

MAGIC = b"NZOA"
VERSION = 1
HEADER_LEN = 100  # Fixed table plus padding that improves the packed NEX
BLOCK_SIZE = 2048
ORDER = [
    "RULES",
    "BOARD",
    "GUI_LOG",
    "MQTT_CONNECT",
    "MQTT_TX",
    "DIRECT",
    "MENU_CONFIG",
    "MENU_LOGIC",
    "SETUP",
    "INPUT_EDIT",
    "SAVELOAD",
    "RESTORE",
    "ABOUT",
    "FILEUI",
    "CONTROL",
]


def write_table(path: Path, entries: list[tuple[int, int]]) -> bool:
    boundaries = [offset for offset, _size in entries]
    if entries:
        boundaries.append(entries[-1][0] + entries[-1][1])
    lines = [
        "; Generated by tools/gen_overlay_atlas.py",
        f"ovl_atlas_count EQU {len(entries)}",
        "ovl_atlas_table:",
    ]
    lines += [f"    DW {boundary}" for boundary in boundaries]
    text = "\n".join(lines) + "\n"
    old = path.read_text(encoding="ascii") if path.exists() else None
    if old != text:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="ascii")
        return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-dir", type=Path, required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--asm-out", type=Path)
    parser.add_argument("--changed-stamp", type=Path)
    parser.add_argument("--bootstrap-asm", action="store_true")
    args = parser.parse_args()

    if args.bootstrap_asm:
        if args.asm_out is None:
            raise SystemExit("--bootstrap-asm requires --asm-out")
        write_table(args.asm_out, [(HEADER_LEN + i * BLOCK_SIZE, BLOCK_SIZE) for i in range(len(ORDER))])
        return 0

    entries: list[tuple[str, bytes]] = []
    for name in ORDER:
        path = args.build_dir / f"{args.name}_{name}.OVL"
        data = path.read_bytes()
        if len(data) > BLOCK_SIZE:
            raise SystemExit(f"{path} too large: {len(data)}")
        entries.append((name, data))

    if HEADER_LEN < 8 + 4 * len(entries):
        raise SystemExit("atlas header too small")

    offset = HEADER_LEN
    table = bytearray()
    payload = bytearray()
    sizes: dict[str, int] = {}
    asm_entries: list[tuple[int, int]] = []
    for name, data in entries:
        table += struct.pack("<HH", offset, len(data))
        payload += data
        sizes[name] = len(data)
        asm_entries.append((offset, len(data)))
        offset += len(data)

    header = bytearray()
    header += MAGIC
    header += bytes((VERSION, len(entries)))
    header += struct.pack("<H", HEADER_LEN)
    header += table
    header += bytes(HEADER_LEN - len(header))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_bytes(bytes(header) + bytes(payload))
    if args.asm_out is not None:
        changed = write_table(args.asm_out, asm_entries)
        if args.changed_stamp is not None:
            args.changed_stamp.write_text("1\n" if changed else "0\n", encoding="ascii")
    sizes["HINTS"] = 0
    sizes["STATUS"] = 0
    sizes["total"] = args.out.stat().st_size
    print(json.dumps(sizes, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
