#!/usr/bin/env python3
"""Generate private resident definitions used by the Next graphics bank."""

from __future__ import annotations

import sys
from pathlib import Path

from gen_overlay_defs import parse_map


REQUIRED_SYMBOLS = (
    "_overlay_code_slot",
    "_spectrum_next_sprites_hide_all",
    "asset_load_size",
    "asset_set_index",
    "next_copy_bundle",
    "nextreg_read",
    "nextreg_write",
)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("Usage: gen_next_graphics_defs.py <map_file>", file=sys.stderr)
        return 2

    symbols = parse_map(Path(argv[1]))
    missing = [name for name in REQUIRED_SYMBOLS if name not in symbols]
    if missing:
        print("Missing symbols: " + ", ".join(missing), file=sys.stderr)
        return 1

    print(";; AUTO-GENERATED by tools/gen_next_graphics_defs.py -- DO NOT EDIT")
    for name in REQUIRED_SYMBOLS:
        print(f"PUBLIC {name}")
        print(f"DEFC {name} = ${symbols[name]:04X}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
