#ifndef NETCHESSZX_SPECTRUM_UI_LAYOUT_H
#define NETCHESSZX_SPECTRUM_UI_LAYOUT_H

#include <stdint.h>

/* screen.asm mirrors the zone coordinates below. */
#define NETCHESSZX_ATTR_BASE ((uint8_t *)0x5800u)

#define NETCHESSZX_TOP_TIMER_ROW 2u
#define NETCHESSZX_TOP_TIMER_SCAN 2u
#define NETCHESSZX_TOP_TIMER_COL 41u
#define NETCHESSZX_TOP_TURN_ROW 3u
#define NETCHESSZX_TOP_TURN_SCAN 2u
#define NETCHESSZX_TOP_TURN_CLEAR_COL 51u
#define NETCHESSZX_STATUS_CLOCK_COL 55u
#define NETCHESSZX_STATUS_TEXT_COL 1u
#define NETCHESSZX_STATUS_SCAN 2u

#define NETCHESSZX_GAME_BOARD_TOP_ROW 5u
#define NETCHESSZX_GAME_BOARD_LEFT_COL 1u

#define NETCHESSZX_INFO_PANEL_COL 18u
#define NETCHESSZX_INFO_TEXT_COL ((NETCHESSZX_INFO_PANEL_COL * 2u) + 1u)
#define NETCHESSZX_INFO_HEADER_ROW NETCHESSZX_GAME_BOARD_TOP_ROW
#define NETCHESSZX_INFO_HEADER_HLINE_ROW 6u
#define NETCHESSZX_INFO_CONTENT_FIRST_ROW 7u
#define NETCHESSZX_INFO_MODE_KEEP 0u
#define NETCHESSZX_INFO_MODE_PREFLIGHT 1u
#define NETCHESSZX_INFO_MODE_SETUP 2u
#define NETCHESSZX_INFO_MODE_GAME 3u
#define NETCHESSZX_INFO_PANEL_CLEAR_FIRST_ROW NETCHESSZX_INFO_HEADER_ROW
#define NETCHESSZX_INFO_NOTICE_ROW 21u
#define NETCHESSZX_INFO_PANEL_CLEAR_LIMIT_ROW (NETCHESSZX_INFO_NOTICE_ROW + 1u)

#define NETCHESSZX_STATUS_ROW 22u
#define NETCHESSZX_INPUT_ROW 23u

#define NETCHESSZX_INPUT_TEXT_MAX 61u
#define NETCHESSZX_INPUT_RENDER_TEXT_SIZE 63u

#define NETCHESSZX_STATUS_TEXT_SIZE 54u
#define NETCHESSZX_STATUS_LEFT_TEXT_SIZE 53u
#define NETCHESSZX_STATUS_CLOCK_TEXT_SIZE 7u
#define NETCHESSZX_NOTICE_TEXT_SIZE 29u
#define NETCHESSZX_GAME_TIMER_TEXT_SIZE 23u

#define NETCHESSZX_MOVE_ROWS 7u
#define NETCHESSZX_MOVE_WHITE_TEXT_SIZE 14u
#define NETCHESSZX_MOVE_BLACK_OFFSET 18u
#define NETCHESSZX_MOVE_BLACK_TEXT_SIZE 13u
#define NETCHESSZX_MOVE_SLOT_SIZE 32u
#define NETCHESSZX_MOVE_BLACK_COL (NETCHESSZX_INFO_TEXT_COL + 14u)

#define NETCHESSZX_CHAT_ROWS 9u
#define NETCHESSZX_CHAT_MESSAGE_TEXT_MAX 42u
#define NETCHESSZX_CHAT_TEXT_SIZE 27u
#define NETCHESSZX_CHAT_SLOT_SIZE (NETCHESSZX_CHAT_TEXT_SIZE + 1u)
/* Bit 7 marks presentation-only control events and is never rendered. */
#define NETCHESSZX_CHAT_EVENT_SIDE_FLAG 0x80u
#define NETCHESSZX_CHAT_TEXT_OFFSET 7u
#define NETCHESSZX_CHAT_TEXT_LIMIT 25u
#define NETCHESSZX_CHAT_ICON_BYTE_COL NETCHESSZX_INFO_PANEL_COL
#define NETCHESSZX_CHAT_TIME_COL (NETCHESSZX_INFO_TEXT_COL + 2u)
#define NETCHESSZX_CHAT_TEXT_COL (NETCHESSZX_INFO_TEXT_COL + 8u)

#define NETCHESSZX_INFO_SETUP_LINE_BASE_ROW NETCHESSZX_INFO_CONTENT_FIRST_ROW
#define NETCHESSZX_INFO_MOVES_FIRST_ROW 6u
#define NETCHESSZX_INFO_MOVES_FIRST_Y 51u
#define NETCHESSZX_INFO_TIGHT_LINE_STEP 6u
#define NETCHESSZX_INFO_CHAT_TITLE_ROW 12u
#define NETCHESSZX_INFO_CHAT_HLINE_ROW 13u
#define NETCHESSZX_INFO_CHAT_FIRST_ROW 16u
#define NETCHESSZX_INFO_CHAT_FIRST_Y 110u

#define NETCHESSZX_SETUP_SCREEN_ROW_BASE NETCHESSZX_INFO_SETUP_LINE_BASE_ROW
#define NETCHESSZX_SETUP_GAME_HEADER_ROW 12u
#define NETCHESSZX_SETUP_ACTION_ROW_WITH_SIDE 20u
#define NETCHESSZX_SETUP_LABEL_BYTE_COL NETCHESSZX_INFO_PANEL_COL
#define NETCHESSZX_SETUP_LEFT_OPTION_BYTE_COL 22u
#define NETCHESSZX_SETUP_RIGHT_OPTION_BYTE_COL 27u
#define NETCHESSZX_SETUP_ACTION_BYTE_COL 29u
#define NETCHESSZX_SETUP_LABEL_ATTR_WIDTH 3u
#define NETCHESSZX_SETUP_COLOR_LABEL_ATTR_WIDTH 4u
#define NETCHESSZX_SETUP_CREATE_ATTR_WIDTH 3u
#define NETCHESSZX_SETUP_JOIN_ATTR_WIDTH 2u
#define NETCHESSZX_SETUP_MQTT_ATTR_WIDTH 2u
#define NETCHESSZX_SETUP_DIRECT_ATTR_WIDTH 3u
#define NETCHESSZX_SETUP_ROOM_ATTR_WIDTH 6u
#define NETCHESSZX_SETUP_DIRECT_HOST_ATTR_WIDTH 8u
#define NETCHESSZX_SETUP_MQTT_HOST_ATTR_WIDTH 6u
#define NETCHESSZX_SETUP_PORT_ATTR_WIDTH 3u
#define NETCHESSZX_SETUP_COLOR_ATTR_WIDTH 3u
#define NETCHESSZX_SETUP_COORD_ATTR_WIDTH 3u
#define NETCHESSZX_SETUP_SAN_ATTR_WIDTH 2u
#define NETCHESSZX_SETUP_HINTS_OFF_ATTR_WIDTH 2u
#define NETCHESSZX_SETUP_HINTS_ON_ATTR_WIDTH 1u
#define NETCHESSZX_SETUP_BOARD_FIRST_BYTE_COL 22u
#define NETCHESSZX_SETUP_BOARD_STEP 2u
#define NETCHESSZX_SETUP_BOARD_SWATCH_CHAR ((char)'\177')
#define NETCHESSZX_SETUP_ACTION_ATTR_WIDTH 3u

#define NETCHESSZX_PREFLIGHT_ROW_BASE NETCHESSZX_INFO_CONTENT_FIRST_ROW
#define NETCHESSZX_PREFLIGHT_ROW_UART_PREFIX "\007"
#define NETCHESSZX_PREFLIGHT_ROW_ESP_PREFIX "\010"
#define NETCHESSZX_PREFLIGHT_ROW_WIFI_PREFIX "\011"
#define NETCHESSZX_PREFLIGHT_ROW_IP_PREFIX "\012"
#define NETCHESSZX_PREFLIGHT_ROW_TIME_PREFIX "\013"

#define NETCHESSZX_SETUP_ROW_GAME_PREFIX "\007"
#define NETCHESSZX_SETUP_ROW_LINK_PREFIX "\010"
#define NETCHESSZX_SETUP_ROW_MQTT_PREFIX "\012"
#define NETCHESSZX_SETUP_ROW_SIDE_PREFIX "\016"
#define NETCHESSZX_SETUP_ROW_NOTATION_PREFIX "\017"
#define NETCHESSZX_SETUP_ROW_BOARD_PREFIX "\020"
#define NETCHESSZX_SETUP_ROW_SET_PREFIX "\021"
#define NETCHESSZX_SETUP_ROW_HINTS_PREFIX "\022"
#define NETCHESSZX_SETUP_ROW_ACTION_PREFIX "\024"
#define NETCHESSZX_SETUP_ROW_ACTION_CHAR ((char)'\024')
#define NETCHESSZX_SETUP_ROW_ACTION_WITH_SIDE_CHAR ((char)'\024')

#endif
