/*
 * rip_icons.c — RIPscrip icon loader for RIPlib
 *
 * Statically-embedded icons: rip_icons_data.c (generated by
 *                            scripts/rip_icons2c.py)
 * Runtime cache:             arena-allocated, keyed by uppercase
 *                            filename (no extension)
 *
 * Copyright (c) 2026 SimVU (Brad Hawthorne)
 * Licensed under the MIT License.  See LICENSE.
 */

#include "rip_icons.h"
#include "rip_icons_data.h"
#include "rip_icns_data.h"
#include <string.h>

static bool name_is_safe(const char *name, int name_len) {
    if (!name || name_len <= 0)
        return false;

    for (int i = 0; i < name_len; i++) {
        unsigned char c = (unsigned char)name[i];
        if (c < 0x20u || c == 0x7Fu)
            return false;
        if (c == '/' || c == '\\' || c == ':')
            return false;
        if (c == '.' && i + 1 < name_len && name[i + 1] == '.')
            return false;
    }
    return true;
}

/* Case-insensitive compare, up to len chars */
static bool name_match(const char *a, int alen, const char *b) {
    if (!a || !b) return false;
    int blen = (int)strlen(b);
    if (alen != blen) return false;
    for (int i = 0; i < alen; i++) {
        char ca = a[i], cb = b[i];
        if (ca >= 'a' && ca <= 'z') ca -= 32;
        if (cb >= 'a' && cb <= 'z') cb -= 32;
        if (ca != cb) return false;
    }
    return true;
}

static int normalize_name(char *dst, const char *name, int name_len) {
    int nlen = name_len;
    if (!dst || !name || name_len <= 0)
        return 0;
    for (int i = 0; i < nlen; i++) {
        if (name[i] == '.') {
            nlen = i;
            break;
        }
    }
    if (nlen > RIP_ICON_NAME_MAX)
        nlen = RIP_ICON_NAME_MAX;
    if (nlen <= 0)
        return 0;
    for (int i = 0; i < nlen; i++) {
        char c = name[i];
        dst[i] = (c >= 'a' && c <= 'z') ? (char)(c - 32) : c;
    }
    dst[nlen] = '\0';
    return nlen;
}

static int runtime_cache_find(const rip_icon_state_t *state,
                              const char *name, int name_len) {
    char key[RIP_ICON_NAME_MAX + 1];
    int key_len;

    if (!state || !name_is_safe(name, name_len))
        return -1;

    key_len = normalize_name(key, name, name_len);
    if (key_len <= 0)
        return -1;

    for (int i = 0; i < state->cache_count; i++) {
        if (name_match(key, key_len, state->cache[i].name))
            return i;
    }
    return -1;
}

static bool runtime_cache_store(rip_icon_state_t *state,
                                const char *name, int name_len,
                                uint8_t *pixels,
                                uint16_t w, uint16_t h,
                                bool replace) {
    char key[RIP_ICON_NAME_MAX + 1];
    int key_len;
    int existing;
    rip_icon_cache_entry_t *e;

    if (!state || !name_is_safe(name, name_len) || !pixels)
        return false;
    if (w == 0 || h == 0 || w > 640 || h > 400)
        return false;

    key_len = normalize_name(key, name, name_len);
    if (key_len <= 0)
        return false;

    existing = runtime_cache_find(state, key, key_len);
    if (existing >= 0) {
        if (!replace)
            return true;
        e = &state->cache[existing];
    } else {
        if (state->cache_count >= RIP_ICON_CACHE_MAX)
            return false;
        e = &state->cache[state->cache_count++];
        memcpy(e->name, key, (size_t)key_len + 1u);
    }

    e->pixels = pixels;
    e->width  = w;
    e->height = h;
    return true;
}

/* ── Arena binding + cache reset ─────────────────────────────────── */

void rip_icon_set_arena(rip_icon_state_t *state, psram_arena_t *arena) {
    if (!state) return;
    state->arena = arena;
    /* Reset the runtime cache: pointers into the old arena are now invalid.
     * Flash-embedded icons (rip_icon_table, rip_icn_table) are unaffected. */
    state->cache_count = 0;
}

/* ── Flash icon lookup ───────────────────────────────────────────── */

bool rip_icon_lookup(const rip_icon_state_t *state,
                     const char *name, int name_len, rip_icon_t *out) {
    char key[RIP_ICON_NAME_MAX + 1];
    int key_len;

    if (!name || name_len <= 0 || !out || !name_is_safe(name, name_len))
        return false;

    key_len = normalize_name(key, name, name_len);
    if (key_len <= 0)
        return false;

    /* 1. Check PSRAM runtime cache so uploaded/generated assets can
     * supersede same-named bundled icons for the current session. */
    if (state) {
        for (int i = 0; i < state->cache_count; i++) {
            if (name_match(key, key_len, state->cache[i].name)) {
                out->pixels = state->cache[i].pixels;
                out->width  = state->cache[i].width;
                out->height = state->cache[i].height;
                return true;
            }
        }
    }

    /* 2. Check flash-embedded BMP table */
    for (int i = 0; i < RIP_ICON_COUNT; i++) {
        if (name_match(key, key_len, rip_icon_table[i].filename)) {
            out->pixels = rip_icon_table[i].pixels;
            out->width  = rip_icon_table[i].width;
            out->height = rip_icon_table[i].height;
            return true;
        }
    }

    /* 2b. Check flash-embedded ICN table */
    for (int i = 0; i < RIP_ICN_COUNT; i++) {
        if (name_match(key, key_len, rip_icn_table[i].filename)) {
            out->pixels = rip_icn_table[i].pixels;
            out->width  = rip_icn_table[i].width;
            out->height = rip_icn_table[i].height;
            return true;
        }
    }

    return false;
}

/* ── BMP parser + PSRAM cache ────────────────────────────────────── */

static bool rip_icon_cache_bmp_impl(rip_icon_state_t *state,
                                    const char *name, int name_len,
                                    const uint8_t *data, int size,
                                    bool replace) {
    int existing;

    if (!state || !name_is_safe(name, name_len) || !data || size < 54)
        return false;
    if (size < 54 || data[0] != 'B' || data[1] != 'M')
        return false;
    existing = runtime_cache_find(state, name, name_len);
    if (existing >= 0 && !replace)
        return true;
    if (existing < 0 && state->cache_count >= RIP_ICON_CACHE_MAX)
        return false;

    /* Parse BMP header */
    uint32_t pixel_offset = (uint32_t)data[10] |
                            ((uint32_t)data[11] << 8) |
                            ((uint32_t)data[12] << 16) |
                            ((uint32_t)data[13] << 24);
    int32_t width  = (int32_t)((uint32_t)data[18] |
                               ((uint32_t)data[19] << 8) |
                               ((uint32_t)data[20] << 16) |
                               ((uint32_t)data[21] << 24));
    int32_t height = (int32_t)((uint32_t)data[22] |
                               ((uint32_t)data[23] << 8) |
                               ((uint32_t)data[24] << 16) |
                               ((uint32_t)data[25] << 24));
    uint16_t bpp   = (uint16_t)data[28] | ((uint16_t)data[29] << 8);
    uint32_t comp  = (uint32_t)data[30] | ((uint32_t)data[31] << 8) |
                     ((uint32_t)data[32] << 16) | ((uint32_t)data[33] << 24);

    if (comp != 0) return false;          /* uncompressed only */
    if (bpp != 4 && bpp != 8) return false;
    if (width <= 0 || width > 640) return false;

    bool bottom_up = (height > 0);
    if (height < 0) height = -height;
    if (height == 0 || height > 400) return false;
    if (pixel_offset >= (uint32_t)size) return false;

    uint64_t row_bytes;
    if (bpp == 4)
        row_bytes = ((((uint64_t)width + 1u) / 2u) + 3u) & ~3u;
    else
        row_bytes = ((uint64_t)width + 3u) & ~3u;

    if (row_bytes == 0) return false;
    {
        uint64_t payload = row_bytes * (uint64_t)height;
        uint64_t end_off = (uint64_t)pixel_offset + payload;
        if (end_off > (uint64_t)(uint32_t)size)
            return false;
    }

    uint32_t pixel_count = (uint32_t)width * (uint32_t)height;
    if (!state->arena) return false;
    uint8_t *pixels = (uint8_t *)psram_arena_alloc(state->arena, pixel_count);
    if (!pixels) return false;

    /* Convert to 8bpp top-down */
    for (int y = 0; y < (int)height; y++) {
        int src_y = bottom_up ? ((int)height - 1 - y) : y;
        size_t row_off = (size_t)pixel_offset + (size_t)src_y * (size_t)row_bytes;
        int dst_off = y * (int)width;

        for (int x = 0; x < (int)width; x++) {
            if (bpp == 4) {
                size_t bi = row_off + (size_t)(x / 2);
                pixels[dst_off + x] = (x & 1) ? (data[bi] & 0x0F) : (data[bi] >> 4);
            } else {
                size_t bi = row_off + (size_t)x;
                pixels[dst_off + x] = data[bi];
            }
        }
    }

    return runtime_cache_store(state, name, name_len, pixels,
                               (uint16_t)width, (uint16_t)height, replace);
}

bool rip_icon_cache_bmp(rip_icon_state_t *state,
                        const char *name, int name_len,
                        const uint8_t *data, int size) {
    return rip_icon_cache_bmp_impl(state, name, name_len, data, size, false);
}

bool rip_icon_cache_bmp_replace(rip_icon_state_t *state,
                                const char *name, int name_len,
                                const uint8_t *data, int size) {
    return rip_icon_cache_bmp_impl(state, name, name_len, data, size, true);
}

bool rip_icon_cache_pixels(rip_icon_state_t *state,
                           const char *name, int name_len,
                           uint8_t *pixels, uint16_t w, uint16_t h) {
    return runtime_cache_store(state, name, name_len, pixels, w, h, false);
}

bool rip_icon_cache_pixels_replace(rip_icon_state_t *state,
                                   const char *name, int name_len,
                                   uint8_t *pixels, uint16_t w, uint16_t h) {
    return runtime_cache_store(state, name, name_len, pixels, w, h, true);
}

bool rip_icon_cache_has_runtime(const rip_icon_state_t *state,
                                const char *name, int name_len) {
    return runtime_cache_find(state, name, name_len) >= 0;
}

int rip_icon_cache_count(const rip_icon_state_t *state) {
    return state ? state->cache_count : 0;
}

/* ── File request queue ──────────────────────────────────────────── */

bool rip_icon_request_file(rip_icon_state_t *state,
                           const char *name, int name_len) {
    if (!state || !name_is_safe(name, name_len) ||
        state->request_count >= RIP_FILE_REQUEST_MAX)
        return false;

    /* Strip extension */
    for (int i = 0; i < name_len; i++) {
        if (name[i] == '.') { name_len = i; break; }
    }
    if (name_len > RIP_FILE_NAME_MAX) name_len = RIP_FILE_NAME_MAX;

    /* Don't queue duplicates */
    for (int i = 0; i < state->request_count; i++) {
        int idx = (state->request_head + i) % RIP_FILE_REQUEST_MAX;
        if (name_match(name, name_len, state->request_queue[idx]))
            return true; /* already queued */
    }

    /* Enqueue — store uppercase */
    char *dst = state->request_queue[state->request_tail];
    for (int i = 0; i < name_len; i++) {
        char c = name[i];
        dst[i] = (c >= 'a' && c <= 'z') ? (c - 32) : c;
    }
    dst[name_len] = '\0';
    state->request_lengths[state->request_tail] = name_len;
    state->request_tail = (state->request_tail + 1) % RIP_FILE_REQUEST_MAX;
    state->request_count++;
    return true;
}

int rip_icon_pending_requests(const rip_icon_state_t *state) {
    return state ? state->request_count : 0;
}

int rip_icon_dequeue_request(rip_icon_state_t *state,
                             char *name_out, int max_len) {
    if (!state || state->request_count == 0 || !name_out || max_len <= 0)
        return 0;

    int len = state->request_lengths[state->request_head];
    if (len <= 0) {
        state->request_head = (state->request_head + 1) % RIP_FILE_REQUEST_MAX;
        state->request_count--;
        return 0;
    }
    if (len >= max_len) len = max_len - 1;
    memcpy(name_out, state->request_queue[state->request_head], (size_t)len);
    name_out[len] = '\0';

    state->request_head = (state->request_head + 1) % RIP_FILE_REQUEST_MAX;
    state->request_count--;
    return len;
}

/* Discard all pending file requests.
 * Called by rip_session_reset() on disconnect so icon requests from
 * the previous BBS session are not carried over to the next connection. */
void rip_icon_clear_requests(rip_icon_state_t *state) {
    if (!state) return;
    state->request_head  = 0;
    state->request_tail  = 0;
    state->request_count = 0;
}
